# Generated by Django 4.1.7 on 2023-02-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodel',
            options={'ordering': ['name'], 'verbose_name': 'Друзья', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='status',
            field=models.CharField(max_length=128, verbose_name='Хто'),
        ),
    ]
